// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using testing.Data;

#nullable disable

namespace testing.Migrations
{
    [DbContext(typeof(LabDbContext))]
    [Migration("20251120011208_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("testing.Models.AksesLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("KartuId")
                        .HasColumnType("integer");

                    b.Property<int>("RuanganId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("TimestampKeluar")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("TimestampMasuk")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("KartuId");

                    b.HasIndex("RuanganId");

                    b.ToTable("AksesLog");
                });

            modelBuilder.Entity("testing.Models.Kartu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("KelasId")
                        .HasColumnType("integer");

                    b.Property<string>("Keterangan")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("AKTIF");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KelasId");

                    b.HasIndex("Uid")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Kartu", t =>
                        {
                            t.HasCheckConstraint("CK_Kartu_SingleOwner", "\"UserId\" IS NULL AND \"KelasId\" IS NOT NULL OR \r\n                      \"UserId\" IS NOT NULL AND \"KelasId\" IS NULL OR \r\n                      \"UserId\" IS NULL AND \"KelasId\" IS NULL");
                        });
                });

            modelBuilder.Entity("testing.Models.Kelas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Kelas");
                });

            modelBuilder.Entity("testing.Models.Ruangan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Ruangan");
                });

            modelBuilder.Entity("testing.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("testing.Models.AksesLog", b =>
                {
                    b.HasOne("testing.Models.Kartu", "Kartu")
                        .WithMany("AksesLogs")
                        .HasForeignKey("KartuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("testing.Models.Ruangan", "Ruangan")
                        .WithMany("AksesLogs")
                        .HasForeignKey("RuanganId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kartu");

                    b.Navigation("Ruangan");
                });

            modelBuilder.Entity("testing.Models.Kartu", b =>
                {
                    b.HasOne("testing.Models.Kelas", "Kelas")
                        .WithMany("Kartu")
                        .HasForeignKey("KelasId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("testing.Models.User", "User")
                        .WithMany("Kartu")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Kelas");

                    b.Navigation("User");
                });

            modelBuilder.Entity("testing.Models.Kartu", b =>
                {
                    b.Navigation("AksesLogs");
                });

            modelBuilder.Entity("testing.Models.Kelas", b =>
                {
                    b.Navigation("Kartu");
                });

            modelBuilder.Entity("testing.Models.Ruangan", b =>
                {
                    b.Navigation("AksesLogs");
                });

            modelBuilder.Entity("testing.Models.User", b =>
                {
                    b.Navigation("Kartu");
                });
#pragma warning restore 612, 618
        }
    }
}
